version: '3.8'

services:
  api:
    restart: unless-stopped
    networks:
      - api-net
    env_file:
      - .env
    ports:
      - '3000:3000'
    build:
      context: .
      dockerfile: Dockerfile

networks:
  api-net:
    name: api-net
    driver: bridge
    external: true